#include "nn/hybrid_engine.hpp"
#include <iostream>
#include <string>
#include <vector>
#include <algorithm>

using namespace s4m;

int main(int argc, char** argv) {
    if (argc < 2) {
        std::cout << "Usage: generate <prompt> [length]\n";
        return 1;
    }

    // Unified Engine parameters
    const size_t NUM_BLOCKS = 4;
    const size_t NUM_CHUNKS = 64; 
    const size_t NUM_PLANES = 512; 

    HybridEngine engine(NUM_BLOCKS, NUM_CHUNKS);

    std::string prompt = argv[1];
    int length = (argc > 2) ? std::stoi(argv[2]) : 100;

    std::cout << "[PROMPT]: " << prompt << "\n[OUTPUT]: ";

    // 1. High-Throughput CAFE-NIS Ingest for Prompt Context
    const uint8_t* p_data = reinterpret_cast<const uint8_t*>(prompt.data());
    size_t p_len = prompt.size();
    size_t processed = 0;

    while (processed < p_len) {
        size_t batch = std::min<size_t>(NUM_CHUNKS, p_len - processed);
        engine.ingest(p_data + processed, batch);
        engine.forward();
        processed += batch;
    }

    // 2. Autoregressive Phase (Byte-by-Byte)
    uint8_t last_byte = p_len > 0 ? p_data[p_len - 1] : 0;
    
    for (int i = 0; i < length; ++i) {
        // Feed the last generated byte back in
        engine.ingest(&last_byte, 1);
        engine.forward();
        
        last_byte = engine.predict();
        
        char c = static_cast<char>(last_byte);
        std::cout << (c >= 32 && c <= 126 ? c : '.');
        std::fflush(stdout); // Immediate flush for "alive" feel
    }

    std::cout << "\n--- DONE ---\n";
    return 0;
}
