import os
import time

# Ensure JAX is installed (Colab already has it, but this is a safeguard)
try:
    import jax
    import jax.numpy as jnp
    from jax import random, vmap, jit
except ImportError:
    print("Please install jax: !pip install jax jaxlib")
    exit(1)

print(f"JAX running on: {jax.devices()}")

# ==============================================================================
# 1. BIOPHYSICAL SIMULATION (JIT COMPILED FOR TPU)
# ==============================================================================

# Constants
NUM_NEURONS = 100
SIM_STEPS = 500  # 500ms of simulation time
DT = 1.0         # 1ms step for synchronous tensor ops

# Connection matrix: Simple 10% random sparse connection per brain
key = random.PRNGKey(42)
weights_topology = random.bernoulli(key, 0.1, (NUM_NEURONS, NUM_NEURONS)).astype(jnp.float32)

@jit
def simulate_brain(genome):
    """
    Simulates a single brain's spiking dynamics for SIM_STEPS.
    genome: [v_thresh, tau_m, calcium_decay, ampa_weight]
    Returns total network spikes.
    """
    v_thresh = genome[0]
    tau_m = genome[1]
    calcium_decay = genome[2]
    ampa_weight = genome[3]

    v_rest = -70.0
    
    # State tracking
    def step_fn(state, _):
        v, ca, spikes = state
        
        # 1. Calcium Decay (Exponential)
        ca = ca * jnp.exp(-DT / calcium_decay)
        
        # 2. Voltage Decay (Leaky Integrate)
        v = v_rest + (v - v_rest) * jnp.exp(-DT / tau_m)
        
        # 3. Synaptic Transmission (Dense Matrix Multiplication)
        # Inward current generated by pre-synaptic spikes hitting AMPA receptors
        synaptic_input = jnp.dot(spikes, weights_topology) * ampa_weight
        v = v + synaptic_input
        
        # Inject constant noise to keep network active
        v = v + 1.0 
        
        # 4. Spike Generation
        new_spikes = jnp.where(v >= v_thresh, 1.0, 0.0)
        
        # 5. Calcium Influx and Voltage Reset
        ca = ca + new_spikes * 10.0
        v = jnp.where(new_spikes > 0.5, v_rest - 5.0, v)
        
        return (v, ca, new_spikes), jnp.sum(new_spikes)

    initial_state = (
        jnp.full((NUM_NEURONS,), v_rest),
        jnp.zeros((NUM_NEURONS,)),
        jnp.zeros((NUM_NEURONS,))
    )

    _, total_spikes_over_time = jax.lax.scan(step_fn, initial_state, None, length=SIM_STEPS)
    
    return jnp.sum(total_spikes_over_time)

# VMAP: This tells the TPU to run all brains in the population simultaneously in a single clock batch!
simulate_population = jit(vmap(simulate_brain))

# ==============================================================================
# 2. ORTHOGONAL NOVELTY EVOLUTIONARY ENGINE
# ==============================================================================

POPULATION_SIZE = 1000  # Massive population thanks to TPU
GENERATIONS = 50
TARGET_SPIKES = 2000.0  # The stable, non-epileptic firing target

@jit
def mutate(genomes, key):
    # Random mutations (-10% to +10%)
    noise = random.uniform(key, genomes.shape, minval=-0.1, maxval=0.1)
    mutated = genomes + (genomes * noise)
    
    # Enforce biological constraints
    mutated = mutated.at[:, 0].set(jnp.clip(mutated[:, 0], -70.0, -20.0))  # v_thresh
    mutated = mutated.at[:, 1].set(jnp.clip(mutated[:, 1], 1.0, 100.0))    # tau_m
    mutated = mutated.at[:, 2].set(jnp.clip(mutated[:, 2], 5.0, 200.0))    # calcium_decay
    mutated = mutated.at[:, 3].set(jnp.clip(mutated[:, 3], 0.001, 10.0))   # ampa_weight
    return mutated

def run_evolution():
    print("Initializing TPUs for Evolution...")
    rng = random.PRNGKey(1337)
    
    # Initialize genomes: [v_thresh, tau_m, calcium_decay, ampa_weight]
    rng, subkey = random.split(rng)
    genomes = jnp.array([[-55.0, 20.0, 50.0, 0.1]] * POPULATION_SIZE)
    genomes = mutate(genomes, subkey) # Initial genetic diversity

    for gen in range(GENERATIONS):
        start_t = time.time()
        
        # 1. Simulate the entire population instantly on TPU
        spikes = simulate_population(genomes)
        
        # 2. Calculate Fitness (Absolute Error)
        fitness_scores = jnp.abs(spikes - TARGET_SPIKES)
        
        # 3. Calculate Orthogonal Novelty Distance from Mean
        pop_mean = jnp.mean(genomes, axis=0)
        novelty_scores = jnp.linalg.norm(genomes - pop_mean, axis=1)
        
        # 4. Orthogonal Sorting
        fitness_ranking = jnp.argsort(fitness_scores)
        novelty_ranking = jnp.argsort(-novelty_scores) # Negative for descending
        
        # Top 10% Fitness Winners
        top_fitness_idx = fitness_ranking[:POPULATION_SIZE // 10]
        winners = genomes[top_fitness_idx]
        
        # Bottom 90% Failures
        failures_idx = fitness_ranking[POPULATION_SIZE // 10:]
        failures = genomes[failures_idx]
        failure_novelty = novelty_scores[failures_idx]
        
        # Top 10% Orthogonal Mutants (from the failures)
        top_novelty_idx = jnp.argsort(-failure_novelty)[:POPULATION_SIZE // 10]
        orthogonal_mutants = failures[top_novelty_idx]
        
        # Combine Winners and Mutants to form parents
        parents = jnp.concatenate([winners, orthogonal_mutants], axis=0)
        
        # 5. Cross-Breed / Clone to fill next generation
        num_parents = parents.shape[0]
        repeats = POPULATION_SIZE // num_parents
        next_gen = jnp.tile(parents, (repeats, 1))
        
        # Add remainder if integer division doesn't perfectly match
        remainder = POPULATION_SIZE - next_gen.shape[0]
        if remainder > 0:
            next_gen = jnp.concatenate([next_gen, parents[:remainder]], axis=0)
            
        # Mutate the new generation
        rng, subkey = random.split(rng)
        genomes = mutate(next_gen, subkey)
        
        end_t = time.time()
        best_spikes = spikes[fitness_ranking[0]]
        best_fitness = fitness_scores[fitness_ranking[0]]
        
        print(f"Gen {gen+1:02d} | Best Fitness Error: {best_fitness:7.2f} (Spikes: {best_spikes:7.2f}) | TPU Gen Time: {(end_t - start_t)*1000:.2f}ms")

    # The ultimate survivor
    final_best_idx = jnp.argmin(jnp.abs(simulate_population(genomes) - TARGET_SPIKES))
    ultimate_genome = genomes[final_best_idx]
    
    print("\n============================================================")
    print("EVOLUTION COMPLETE. THE BLACK BOX HAS SOLVED THE BIOPHYSICS.")
    print("============================================================")
    print("Final Optimal Genomic Parameters:")
    print(f"  V_THRESH:           {ultimate_genome[0]:.4f} mV")
    print(f"  TAU_M:              {ultimate_genome[1]:.4f} ms")
    print(f"  CALCIUM_DECAY:      {ultimate_genome[2]:.4f} ms")
    print(f"  AMPA_VOLTAGE_JUMP:  {ultimate_genome[3]:.4f} mV")
    print("============================================================")
    print("Copy these values back into the C++ brain_tree.hpp Engine.")

if __name__ == "__main__":
    run_evolution()
